# Generated by Django 2.1.5 on 2019-01-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190111_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedpost',
            name='people',
        ),
        migrations.RemoveField(
            model_name='likedpost',
            name='post',
        ),
        migrations.AddField(
            model_name='people',
            name='likedPosts',
            field=models.ManyToManyField(to='people.Post'),
        ),
        migrations.DeleteModel(
            name='LikedPost',
        ),
    ]
